// CRUD helper functions
// Extracted from crud.ts to reduce file size and improve maintainability

import { and, eq, inArray } from 'drizzle-orm';
import type {
  CMSField,
  IntrospectedColumn,
  IntrospectedSchema,
  IntrospectedTable,
  JunctionTable,
} from '@hotsauce/core';
import {
  createInsertSchema,
  createUpdateSchema,
  mapColumnToField,
  mapColumnToFieldType,
} from '@hotsauce/core';
import { ZodError } from 'zod';
import type { ManyToManyData, RelationOption } from '@hotsauce/ui';
import type { ManyToManyDisplayData } from '@hotsauce/ui';
import type { ParserFn, ResolvedCmsOptions } from './types.ts';
import { cmsUrl, formatTableName } from './router.ts';
import { isAuditTimestampColumn, propertyNameToLabel } from '@hotsauce/core';
import type { ListColumn, NavItem } from '@hotsauce/ui';

// ============================================================================
// Navigation helpers
// ============================================================================

export interface BuildNavItemsOptions {
  /** Optional list of table names allowed by policy. If provided, only these tables appear in nav. */
  allowedByPolicy?: string[];
}

export function buildNavItems(
  schema: IntrospectedSchema,
  basePath: string,
  activeTable?: string,
  options?: BuildNavItemsOptions,
): NavItem[] {
  // Filter out junction tables and tables marked as hidden via $cms({ hidden: true })
  let visibleTables = schema.tables.filter((t) =>
    !t.isJunction && !t.cmsOptions?.hidden
  );

  // If policy-allowed list is provided, further filter to only those tables
  if (options?.allowedByPolicy) {
    const allowedSet = new Set(options.allowedByPolicy);
    visibleTables = visibleTables.filter((t) => allowedSet.has(t.name));
  }

  return [
    {
      href: cmsUrl(basePath),
      label: 'Dashboard',
      active: !activeTable,
      dividerAfter: true,
    },
    ...visibleTables.map((t) => ({
      href: cmsUrl(basePath, t.name),
      label: formatTableName(t.name),
      active: t.name === activeTable,
    })),
  ];
}

// ============================================================================
// Record helpers
// ============================================================================

export function getPrimaryKeyColumn(
  table: IntrospectedTable,
): IntrospectedColumn {
  const pk = table.columns.find((c) => c.isPrimaryKey);
  if (!pk) {
    throw new Error(`Table ${table.name} has no primary key`);
  }
  return pk;
}

export function getPrimaryKeyValue(
  table: IntrospectedTable,
  record: Record<string, unknown>,
): string {
  const pk = getPrimaryKeyColumn(table);
  return String(record[pk.propertyName] ?? '');
}

/**
 * Check if a column is auto-generated (shouldn't be user-editable).
 * Includes auto-increment PKs and common timestamp columns.
 */
export function isAutoGeneratedColumn(col: IntrospectedColumn): boolean {
  // Auto-increment PK (serial, identity, uuid with default)
  if (col.isPrimaryKey && col.hasDefault) return true;
  // Common auto-managed timestamp columns
  if (isAuditTimestampColumn(col)) return true;
  return false;
}

export function getEditableColumns(
  table: IntrospectedTable,
): IntrospectedColumn[] {
  return table.columns.filter((c) => !isAutoGeneratedColumn(c));
}

/**
 * Structural check: can this table support INSERT … DEFAULT VALUES?
 * Returns true if every column either has a default (incl. auto-PK) or is nullable.
 *
 * Used by validateAutoDraft (startup) and handleCreate (runtime).
 * The autoDraft table option gates whether this check is consulted.
 */
export function canAutoCreateDraft(table: IntrospectedTable): boolean {
  return table.columns.every((col) => {
    if (col.isPrimaryKey && col.hasDefault) return true;
    if (col.hasDefault) return true;
    if (!col.notNull) return true;
    return false;
  });
}

// ============================================================================
// Column/field helpers
// ============================================================================

export function getListColumns(table: IntrospectedTable): ListColumn[] {
  return table.columns
    .filter((c) => {
      // Exclude columns marked as hidden via $cms({ hidden: true })
      if (c.cmsOptions?.hidden) return false;
      // Exclude large text fields from list
      const fieldType = mapColumnToFieldType(c);
      if (fieldType === 'textarea' || fieldType === 'json') return false;
      return true;
    })
    .slice(0, 6)
    .map((c) => ({
      key: c.propertyName,
      label: propertyNameToLabel(c.propertyName),
    }));
}

export function tableToCmsFields(
  table: IntrospectedTable,
  editableOnly = false,
): CMSField[] {
  let columns = table.columns;
  if (editableOnly) {
    columns = getEditableColumns(table);
  }

  return columns.map((col) => mapColumnToField(col));
}

export function recordToValues(
  formData: Record<string, string | string[]>,
): Record<string, unknown> {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(formData)) {
    result[key] = Array.isArray(value) ? value[0] : value;
  }
  return result;
}

// ============================================================================
// Relation helpers
// ============================================================================

/**
 * Get the best display column for a table (for relation labels)
 * Looks for common naming patterns: name, title, label, email, etc.
 */
export function getDisplayColumn(
  table: IntrospectedTable,
): IntrospectedColumn | null {
  const preferredNames = [
    'name',
    'title',
    'label',
    'email',
    'username',
    'slug',
  ];

  for (const name of preferredNames) {
    const col = table.columns.find((c) =>
      c.propertyName === name || c.dbName === name
    );
    if (col && col.dataType === 'string') {
      return col;
    }
  }

  // Fall back to first non-PK string column
  const stringCol = table.columns.find((c) =>
    c.dataType === 'string' && !c.isPrimaryKey
  );
  if (stringCol) return stringCol;

  // Last resort: first non-PK column
  return table.columns.find((c) => !c.isPrimaryKey) ?? null;
}

/**
 * Fetch all records from a related table for FK picker
 */
export async function fetchRelationOptions(
  options: ResolvedCmsOptions,
  tableName: string,
): Promise<RelationOption[]> {
  const table = options.introspected.tables.find((t) => t.name === tableName);
  if (!table) return [];

  const drizzleTable = table.table;
  const pkColumn = table.columns.find((c) => c.isPrimaryKey);
  const displayColumn = getDisplayColumn(table);

  if (!pkColumn) return [];

  try {
    const records = await options.db.select().from(drizzleTable).limit(500);

    return (records as Record<string, unknown>[]).map((record) => {
      const value = record[pkColumn.propertyName];
      const label = displayColumn
        ? String(record[displayColumn.propertyName] ?? value)
        : String(value);

      return {
        value: value as string | number,
        label,
      };
    });
  } catch {
    return [];
  }
}

/**
 * Fetch relation options for all FK columns in a table
 */
export async function fetchAllRelationOptions(
  options: ResolvedCmsOptions,
  table: IntrospectedTable,
): Promise<Record<string, RelationOption[]>> {
  const relationData: Record<string, RelationOption[]> = {};

  // Find all columns with foreign key references
  const fkColumns = table.columns.filter((c) => c.references);

  // Fetch options for each FK column in parallel
  // Use propertyName as key since that's what forms use for field lookup
  await Promise.all(
    fkColumns.map(async (col) => {
      if (col.references) {
        relationData[col.propertyName] = await fetchRelationOptions(
          options,
          col.references.table,
        );
      }
    }),
  );

  return relationData;
}

// ============================================================================
// Many-to-many helpers
// ============================================================================

/**
 * Get junctions where this table is involved (either side)
 */
export function getJunctionsForTable(
  junctions: JunctionTable[],
  tableName: string,
): {
  junction: JunctionTable;
  relatedTable: string;
  thisColumn: string;
  relatedColumn: string;
}[] {
  const result: {
    junction: JunctionTable;
    relatedTable: string;
    thisColumn: string;
    relatedColumn: string;
  }[] = [];

  for (const junction of junctions) {
    if (junction.leftTable === tableName) {
      result.push({
        junction,
        relatedTable: junction.rightTable,
        thisColumn: junction.leftColumn,
        relatedColumn: junction.rightColumn,
      });
    } else if (junction.rightTable === tableName) {
      result.push({
        junction,
        relatedTable: junction.leftTable,
        thisColumn: junction.rightColumn,
        relatedColumn: junction.leftColumn,
      });
    }
  }

  return result;
}

/**
 * Fetch many-to-many data for a record being edited
 */
export async function fetchManyToManyData(
  options: ResolvedCmsOptions,
  table: IntrospectedTable,
  recordId: string | number | undefined,
): Promise<ManyToManyData[]> {
  const junctions = getJunctionsForTable(
    options.introspected.junctions,
    table.name,
  );
  if (junctions.length === 0) return [];

  const result: ManyToManyData[] = [];

  for (
    const { junction, relatedTable, thisColumn, relatedColumn } of junctions
  ) {
    // Find the junction table
    const junctionTableInfo = options.introspected.tables.find((t) =>
      t.name === junction.tableName
    );
    if (!junctionTableInfo) continue;

    // Find the related table
    const relatedTableInfo = options.introspected.tables.find((t) =>
      t.name === relatedTable
    );
    if (!relatedTableInfo) continue;

    // Fetch all options from the related table
    const allOptions = await fetchRelationOptions(options, relatedTable);

    // Fetch current selections if we have a recordId (edit mode)
    let selectedValues: (string | number)[] = [];
    if (recordId !== undefined) {
      try {
        const junctionTable = junctionTableInfo.table;
        // Find the column that points to this table
        const junctionThisCol = junctionTableInfo.columns.find((c) =>
          c.propertyName === thisColumn
        );
        const junctionRelatedCol = junctionTableInfo.columns.find((c) =>
          c.propertyName === relatedColumn
        );

        if (junctionThisCol && junctionRelatedCol) {
          // deno-lint-ignore no-explicit-any
          const drizzleCol = (junctionTable as any)[thisColumn];
          if (drizzleCol) {
            const rows = await options.db
              .select()
              .from(junctionTable)
              .where(eq(drizzleCol, recordId));

            selectedValues = (rows as Record<string, unknown>[]).map(
              (row) => row[relatedColumn] as string | number,
            );
          }
        }
      } catch {
        // Ignore errors fetching selections
      }
    }

    result.push({
      fieldName: `${relatedTable}Ids`,
      label: formatTableName(relatedTable),
      relatedTable,
      options: allOptions,
      selectedValues,
    });
  }

  return result;
}

/**
 * Fetch many-to-many display data for list/detail views
 * Returns a Map from record ID to array of display data
 */
export async function fetchManyToManyDisplayData(
  options: ResolvedCmsOptions,
  table: IntrospectedTable,
  recordIds: (string | number)[],
): Promise<Map<string | number, ManyToManyDisplayData[]>> {
  const result = new Map<string | number, ManyToManyDisplayData[]>();
  if (recordIds.length === 0) return result;

  // Initialize empty arrays for all records
  for (const id of recordIds) {
    result.set(id, []);
  }

  const junctions = getJunctionsForTable(
    options.introspected.junctions,
    table.name,
  );
  if (junctions.length === 0) return result;

  for (
    const { junction, relatedTable, thisColumn, relatedColumn } of junctions
  ) {
    // Find the junction table
    const junctionTableInfo = options.introspected.tables.find((t) =>
      t.name === junction.tableName
    );
    if (!junctionTableInfo) continue;

    // Find the related table
    const relatedTableInfo = options.introspected.tables.find((t) =>
      t.name === relatedTable
    );
    if (!relatedTableInfo) continue;

    // Fetch all options from the related table (for display labels)
    const allOptions = await fetchRelationOptions(options, relatedTable);
    const optionLabels = new Map(
      allOptions.map((o) => [String(o.value), o.label]),
    );

    // Fetch junction rows for all recordIds at once
    try {
      const junctionTable = junctionTableInfo.table;
      // deno-lint-ignore no-explicit-any
      const drizzleCol = (junctionTable as any)[thisColumn];
      if (drizzleCol) {
        const rows = await options.db
          .select()
          .from(junctionTable)
          .where(inArray(drizzleCol, recordIds as number[]));

        // Group by this table's ID
        const groupedByRecord = new Map<string | number, (string | number)[]>();
        for (const row of rows as Record<string, unknown>[]) {
          const recordId = row[thisColumn] as string | number;
          const relatedId = row[relatedColumn] as string | number;
          if (!groupedByRecord.has(recordId)) {
            groupedByRecord.set(recordId, []);
          }
          groupedByRecord.get(recordId)!.push(relatedId);
        }

        // Build display data for each record
        for (const id of recordIds) {
          const selectedIds = groupedByRecord.get(id) ?? [];
          const displayValues = selectedIds.map((relId) =>
            optionLabels.get(String(relId)) ?? String(relId)
          );

          result.get(id)!.push({
            fieldName: `${relatedTable}Ids`,
            label: formatTableName(relatedTable),
            displayValues,
          });
        }
      }
    } catch {
      // Ignore errors - M2M columns won't show
    }
  }

  return result;
}

/**
 * Save many-to-many junction data after creating/updating a record
 */
export async function saveManyToManyData(
  options: ResolvedCmsOptions,
  table: IntrospectedTable,
  recordId: string | number,
  formData: Record<string, string | string[]>,
): Promise<void> {
  const junctions = getJunctionsForTable(
    options.introspected.junctions,
    table.name,
  );
  if (junctions.length === 0) return;

  for (
    const { junction, relatedTable, thisColumn, relatedColumn } of junctions
  ) {
    // Get field name for this relation
    const fieldName = `${relatedTable}Ids`;
    const rawValues = formData[fieldName];

    // Parse selected values from form
    const selectedIds = new Set<string>();
    if (rawValues) {
      const values = Array.isArray(rawValues) ? rawValues : [rawValues];
      for (const v of values) {
        if (v) selectedIds.add(v);
      }
    }

    // Find the junction table
    const junctionTableInfo = options.introspected.tables.find((t) =>
      t.name === junction.tableName
    );
    if (!junctionTableInfo) continue;

    const junctionTable = junctionTableInfo.table;
    // deno-lint-ignore no-explicit-any
    const drizzleThisCol = (junctionTable as any)[thisColumn];
    // deno-lint-ignore no-explicit-any
    const drizzleRelatedCol = (junctionTable as any)[relatedColumn];

    if (!drizzleThisCol || !drizzleRelatedCol) continue;

    try {
      // Get existing junction rows for this record
      const existingRows = await options.db
        .select()
        .from(junctionTable)
        .where(eq(drizzleThisCol, recordId));

      const existingIds = new Set(
        (existingRows as Record<string, unknown>[]).map((r) =>
          String(r[relatedColumn])
        ),
      );

      // Calculate what to delete and insert
      const toDelete = [...existingIds].filter((id) => !selectedIds.has(id));
      const toInsert = [...selectedIds].filter((id) => !existingIds.has(id));

      // Delete removed relations
      if (toDelete.length > 0) {
        await options.db
          .delete(junctionTable)
          .where(and(
            eq(drizzleThisCol, recordId),
            inArray(
              drizzleRelatedCol,
              toDelete.map((id) => parseInt(id, 10) || id),
            ),
          ));
      }

      // Insert new relations
      if (toInsert.length > 0) {
        const insertValues = toInsert.map((relatedId) => ({
          [thisColumn]: recordId,
          [relatedColumn]: parseInt(relatedId, 10) || relatedId,
        }));
        await options.db.insert(junctionTable).values(insertValues);
      }
    } catch {
      // Log but don't fail the whole operation
    }
  }
}

// ============================================================================
// Error handling
// ============================================================================

/**
 * Database error codes for common constraint violations
 */
const FK_VIOLATION_PATTERNS = [
  '23503', // Postgres FK violation code
  'SQLITE_CONSTRAINT_FOREIGNKEY',
  'ER_ROW_IS_REFERENCED', // MySQL
];

const UNIQUE_VIOLATION_PATTERNS = [
  '23505', // Postgres unique violation
  'SQLITE_CONSTRAINT_UNIQUE',
  'ER_DUP_ENTRY', // MySQL
];

/**
 * Check if an error is a foreign key violation
 */
export function isForeignKeyViolation(error: unknown): boolean {
  const errorCode = (error as { code?: string })?.code;
  const errorMessage = error instanceof Error ? error.message : String(error);
  const causedBy =
    (error as { cause?: { message?: string } })?.cause?.message ?? '';
  const fullMessage = `${errorMessage} ${causedBy}`.toLowerCase();

  if (errorCode && FK_VIOLATION_PATTERNS.includes(errorCode)) {
    return true;
  }

  return fullMessage.includes('foreign key constraint') ||
    fullMessage.includes('foreign key') ||
    fullMessage.includes('violates foreign key');
}

/**
 * Check if an error is a unique constraint violation
 */
export function isUniqueViolation(error: unknown): boolean {
  const errorCode = (error as { code?: string })?.code;
  const errorMessage = error instanceof Error ? error.message : String(error);
  const causedBy =
    (error as { cause?: { message?: string } })?.cause?.message ?? '';
  const fullMessage = `${errorMessage} ${causedBy}`.toLowerCase();

  if (errorCode && UNIQUE_VIOLATION_PATTERNS.includes(errorCode)) {
    return true;
  }

  return fullMessage.includes('unique constraint') ||
    fullMessage.includes('duplicate key') ||
    fullMessage.includes('unique');
}

/**
 * Get a safe, user-friendly error message from a database error
 * Never exposes raw error details to the user
 */
export function getSafeErrorMessage(
  error: unknown,
  action: 'create' | 'update' | 'delete',
): string {
  if (isForeignKeyViolation(error)) {
    if (action === 'delete') {
      return 'Cannot delete this record because it is referenced by other records. Remove those references first.';
    }
    return 'The selected reference does not exist. Please choose a valid option.';
  }

  if (isUniqueViolation(error)) {
    return 'A record with these values already exists. Please use different values.';
  }

  // Generic safe messages based on action
  switch (action) {
    case 'create':
      return 'Failed to create the record. Please check your input and try again.';
    case 'update':
      return 'Failed to update the record. Please check your input and try again.';
    case 'delete':
      return 'Failed to delete the record. Please try again.';
  }
}

// ============================================================================
// Form validation
// ============================================================================

/**
 * Result of validating form data against a Zod schema
 */
export interface ValidationResult<T = Record<string, unknown>> {
  success: boolean;
  data?: T;
  errors?: Record<string, string>;
  formError?: string;
}

/**
 * Format Zod errors into a field-keyed error object
 * Returns errors keyed by propertyName for display in forms
 */
export function formatZodErrors(zodError: ZodError): Record<string, string> {
  const errors: Record<string, string> = {};

  for (const issue of zodError.issues) {
    // Use the first path segment as the field name
    const fieldName = issue.path[0];
    if (typeof fieldName === 'string' && !errors[fieldName]) {
      errors[fieldName] = issue.message;
    }
  }

  return errors;
}

/**
 * Validate form data against the Drizzle table's schema
 * Uses drizzle-zod's createInsertSchema or createUpdateSchema based on mode
 *
 * @param drizzleTable - The Drizzle table definition
 * @param values - Coerced form values to validate
 * @param mode - 'insert' for new records (required fields enforced), 'update' for edits (all fields optional)
 * @returns Validation result with field-specific errors
 */
export function validateFormData(
  drizzleTable: unknown,
  values: Record<string, unknown>,
  mode: 'insert' | 'update' = 'insert',
): ValidationResult {
  try {
    // Generate appropriate Zod schema from Drizzle table
    // - createInsertSchema: required fields must be present (for new records)
    // - createUpdateSchema: all fields optional (for partial updates)
    const tableArg = drizzleTable as Parameters<typeof createInsertSchema>[0];
    const schema = mode === 'insert'
      ? createInsertSchema(tableArg)
      : createUpdateSchema(tableArg);

    // Validate the values
    const result = schema.safeParse(values);

    if (result.success) {
      return {
        success: true,
        data: result.data as Record<string, unknown>,
      };
    }

    // Format errors for form display
    const errors = formatZodErrors(result.error);

    return {
      success: false,
      errors,
      formError: Object.keys(errors).length > 0
        ? 'Please fix the errors below.'
        : 'Validation failed. Please check your input.',
    };
  } catch (err) {
    // Schema generation failed - throw so caller can handle appropriately.
    // This can happen with complex table types not fully supported by drizzle-zod
    // (e.g., custom types, certain array configurations, or dialect-specific features).
    const message = err instanceof Error ? err.message : String(err);
    throw new Error(`Zod schema generation failed: ${message}`);
  }
}

/**
 * Validate form data using custom parser if provided, otherwise use drizzle-zod
 *
 * @param options - Resolved CMS options containing custom parsers
 * @param tableName - Name of the table being validated
 * @param drizzleTable - The Drizzle table definition (for fallback)
 * @param values - Coerced form values to validate
 * @param mode - 'insert' or 'update'
 * @returns Validation result with field-specific errors
 */
export function validateWithParsers(
  options: ResolvedCmsOptions,
  tableName: string,
  drizzleTable: unknown,
  values: Record<string, unknown>,
  mode: 'insert' | 'update',
): ValidationResult {
  const customParser: ParserFn | undefined = options.parsers[tableName]?.[mode];

  if (customParser) {
    try {
      const data = customParser(values) as Record<string, unknown>;
      return { success: true, data };
    } catch (error) {
      // Extract field errors from the error
      const errors: Record<string, string> = {};

      if (error instanceof ZodError) {
        // ZodError has type-safe access to issues
        for (const issue of error.issues) {
          const fieldName = issue.path[0];
          if (typeof fieldName === 'string' && !errors[fieldName]) {
            errors[fieldName] = issue.message;
          }
        }
      } else {
        // Try Valibot-style errors as fallback
        const err = error as {
          errors?: Array<{ path?: string; message?: string }>;
        };
        if (err.errors) {
          for (const e of err.errors) {
            if (e.path && !errors[e.path]) {
              errors[e.path] = e.message ?? 'Invalid value';
            }
          }
        }
      }

      const hasFieldErrors = Object.keys(errors).length > 0;
      return {
        success: false,
        errors: hasFieldErrors ? errors : undefined,
        formError: hasFieldErrors
          ? 'Please fix the errors below.'
          : (error instanceof Error ? error.message : 'Validation failed'),
      };
    }
  }

  // Fall back to drizzle-zod
  try {
    return validateFormData(drizzleTable, values, mode);
  } catch (error) {
    // Schema generation failed - log via onError and block the operation
    if (options.onError) {
      options.onError(
        error instanceof Error ? error : new Error(String(error)),
        {
          source: 'handler',
          request: new Request('http://localhost/validation'),
          url: new URL('http://localhost/validation'),
          route: null,
          action: mode === 'insert' ? 'create' : 'update',
        },
      );
    }

    // Return explicit failure - don't silently pass unvalidated data
    return {
      success: false,
      formError:
        'Validation unavailable for this table. Please provide a custom parser or contact the administrator.',
    };
  }
}
